//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesite.Services.AddressBroker.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JB_Service_InfoEntities : DbContext
    {
        public JB_Service_InfoEntities()
            : base("name=JB_Service_InfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JB_LookupType> JB_LookupType { get; set; }
        public virtual DbSet<JB_MapFormat> JB_MapFormat { get; set; }
        public virtual DbSet<JB_Maps> JB_Maps { get; set; }
        public virtual DbSet<JB_Maps_OutputFields> JB_Maps_OutputFields { get; set; }
        public virtual DbSet<JB_OutputField> JB_OutputField { get; set; }
        public virtual DbSet<JB_State_Maps> JB_State_Maps { get; set; }
        public virtual DbSet<JB_States> JB_States { get; set; }
    }
}
