//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesite.Services.AddressBroker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JB_State_Maps
    {
        public int StateMapId { get; set; }
        public int StateId { get; set; }
        public int MapId { get; set; }
    
        public virtual JB_Maps JB_Maps { get; set; }
        public virtual JB_States JB_States { get; set; }
    }
}
